version: '3.9'
services:
  node:
    image: adbarclay92/sdc-node
    container_name: sdc-node
    ports:
      - 1234:3000
    build:
      context: ../../
      dockerfile: ./scripts/docker/node.Dockerfile
