version: '3.9'
services:
  node:
    image: sdc-node
    container_name: sdc-node
    ports:
      - 3000:1234
    build:
      dockerfile: ./scripts/docker/node.Dockerfile
      context: ../../
  postgres:
    image: sdc-postgres
    container_name: sdc-postgres
    ports:
      - 3002:5432
    environment:
      POSTGRES_PASSWORD: postgres
    build:
      context: ../../
      dockerfile: ./scripts/docker/postgres.Dockerfile
